name:                custom-rules-in-shake16
version:             0.1.0.0
github:              "sheyll/custom-rules-in-shake16"
license:             BSD3
author:              "Sven Heyll"
maintainer:          "sven.heyll@gmail.com"
copyright:           "Copyright Sven Heyll"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Tutorial on how to write custom rules with Shake 0.16.3
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/sheyll/custom-rules-in-shake16#readme>

dependencies:
- base >= 4.7 && < 5
- shake >= 0.16.3

library:
  source-dirs: src

